### ISSUE TITLE
verbose_name ბის წინ რატომ გაქვს ადგილი გამოტოვებული?

### ISSUE THREAD

**Issue by MariamKipshidze** [ikakopa1985/Django-Initial#13]
https://github.com/ikakopa1985/Django-Initial/blob/981815b3c1b25ba9006232ec7e01efd0497f629e/myproject/market/models.py#L9C45-L9C57

**Comment by ikakopa1985** [comment]
როცა verbose-name ქართულია ბრაუზერი პირველ სიმბოლოს დიდ სიმბოლოდ აქცევს და აღარ იკითხება
