### ISSUE TITLE
ციკლის მაგივრად შეგიძლია გამოიყენეო value_list() და მერე ან სერიალაიზერი ან ლისტად კონვერტაცია

### ISSUE THREAD

**Issue by MariamKipshidze** [ikakopa1985/Django-Initial#15]
https://github.com/ikakopa1985/Django-Initial/blob/f65700ed4e4c8c2c1b0c4ce3c6bc4a90b5930ecb/myproject/market/views.py#L78

**Comment by ikakopa1985** [comment]
value_list() და მერე ან სერიალაიზერი           გამოყენებული მაქ სხვა ფუქციაში ეს მეთოდიც დავტოვე ნიმუშად

**Comment by MariamKipshidze** [comment]
კარგი ნიმუშად თუ გინდა იყოს, მაგრამ შეფიძლია კომენტარის შიგნით დატოვე სხვა ვერსიები
