### ISSUE TITLE
კარგი და მოსახერებელი პრაქტიკაა მოკავშირე ფილდები მოდელის თავში მოაქციო რომ აღსაქმელად უფრო მარტივი იყოს

### ISSUE THREAD

**Issue by MariamKipshidze** [ikakopa1985/Django-Initial#5]
https://github.com/ikakopa1985/Django-Initial/blob/e5a1de6a3b4e4b31b77ce0ad476e5e3eb622c36b/myproject/market/models.py#L9

**Comment by ikakopa1985** [comment]
ვერ მივხვდი მარიამ რას გულისხმობ

**Comment by MariamKipshidze** [comment]
FK, M2M, O2M ფილდები არიას მოკალვშირე ფილდები და მოდელის ტავში რომ ეწეროს სხვა ფილდების თავზე
